// @generated by protoc-gen-connect-web v0.2.0 with parameter "target=js+dts"
// @generated from file parca/profilestore/v1alpha1/profilestore.proto (package parca.profilestore.v1alpha1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {WriteRawRequest, WriteRawResponse} from "./profilestore_pb";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * ProfileStoreService is the service the accepts pprof writes
 *
 * @generated from service parca.profilestore.v1alpha1.ProfileStoreService
 */
export declare const ProfileStoreService: {
  readonly typeName: "parca.profilestore.v1alpha1.ProfileStoreService",
  readonly methods: {
    /**
     * WriteRaw accepts a raw set of bytes of a pprof file
     *
     * @generated from rpc parca.profilestore.v1alpha1.ProfileStoreService.WriteRaw
     */
    readonly writeRaw: {
      readonly name: "WriteRaw",
      readonly I: typeof WriteRawRequest,
      readonly O: typeof WriteRawResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

