// @generated by protoc-gen-connect-web v0.2.0 with parameter "target=js+dts"
// @generated from file parca/profilestore/v1alpha1/profilestore.proto (package parca.profilestore.v1alpha1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {WriteRawRequest, WriteRawResponse} from "./profilestore_pb";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * ProfileStoreService is the service the accepts pprof writes
 *
 * @generated from service parca.profilestore.v1alpha1.ProfileStoreService
 */
export const ProfileStoreService = {
  typeName: "parca.profilestore.v1alpha1.ProfileStoreService",
  methods: {
    /**
     * WriteRaw accepts a raw set of bytes of a pprof file
     *
     * @generated from rpc parca.profilestore.v1alpha1.ProfileStoreService.WriteRaw
     */
    writeRaw: {
      name: "WriteRaw",
      I: WriteRawRequest,
      O: WriteRawResponse,
      kind: MethodKind.Unary,
    },
  }
};

