// @generated by protoc-gen-connect-web v0.2.0 with parameter "target=js+dts"
// @generated from file parca/scrape/v1alpha1/scrape.proto (package parca.scrape.v1alpha1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {TargetsRequest, TargetsResponse} from "./scrape_pb";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * ScrapeService maintains the set of scrape targets
 *
 * @generated from service parca.scrape.v1alpha1.ScrapeService
 */
export declare const ScrapeService: {
  readonly typeName: "parca.scrape.v1alpha1.ScrapeService",
  readonly methods: {
    /**
     * Targets returns the set of scrape targets that are configured
     *
     * @generated from rpc parca.scrape.v1alpha1.ScrapeService.Targets
     */
    readonly targets: {
      readonly name: "Targets",
      readonly I: typeof TargetsRequest,
      readonly O: typeof TargetsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

